[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.geojson"
  [headers.values]
    Content-Type = "application/geo+json"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.csv"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
